// frontend-angular/src/app/app.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { Folder, FileItem, TreeFolder, RoadmapData } from './models';
import { ApiService } from './services/api.service';
import { FolderTreeComponent } from './components/folder-tree/folder-tree.component';
import { RoadmapEditorComponent } from './components/roadmap-editor/roadmap-editor.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FolderTreeComponent, RoadmapEditorComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit {
  private api = inject(ApiService);

  loading = false;
  error: string | null = null;
  folderTree: TreeFolder[] = [];
  filesByFolderId = new Map<string, FileItem[]>();
  currentFolderId: string | null = null;
  currentFolderPath: Folder[] = [];
  childFolders: Folder[] = [];
  files: FileItem[] = [];
  expandedIds = new Set<string>();

  editingRoadmapFile: FileItem | null = null;
  roadmapData: RoadmapData | null = null;
  roadmapSaving = false;
  dropZoneActive = false;

  ngOnInit(): void {
    this.loadTree().then(() => this.selectFolder(null));
  }

  isRoadmapFile(file: FileItem): boolean {
    return file.name.toLowerCase().endsWith('.roadmap');
  }

  private getPathToId(nodes: TreeFolder[], targetId: string, path: string[] = []): string[] | null {
    for (const n of nodes) {
      const p = [...path, n.id];
      if (n.id === targetId) return p;
      const found = this.getPathToId(n.children, targetId, p);
      if (found) return found;
    }
    return null;
  }

  private getPathNodes(nodes: TreeFolder[], targetId: string, path: TreeFolder[] = []): TreeFolder[] | null {
    for (const n of nodes) {
      const p = [...path, n];
      if (n.id === targetId) return p;
      const found = this.getPathNodes(n.children, targetId, p);
      if (found) return found;
    }
    return null;
  }

  private expandPathTo(id: string | null): void {
    if (id === null) return;
    const path = this.getPathToId(this.folderTree, id);
    if (path) this.expandedIds = new Set(path);
  }

  onExpandToggle(id: string): void {
    this.expandedIds = new Set(this.expandedIds);
    if (this.expandedIds.has(id)) this.expandedIds.delete(id);
    else this.expandedIds.add(id);
  }

  async loadTree(): Promise<void> {
    try {
      const [tree, allFiles] = await Promise.all([
        this.api.getFolderTree(),
        this.api.getFiles(),
      ]);
      this.folderTree = tree;
      const byFolder = new Map<string, FileItem[]>();
      for (const file of allFiles) {
        const list = byFolder.get(file.folderId) ?? [];
        list.push(file);
        byFolder.set(file.folderId, list);
      }
      this.filesByFolderId = byFolder;
    } catch {
      this.folderTree = [];
      this.filesByFolderId = new Map();
    }
  }

  async selectFolder(id: string | null): Promise<void> {
    this.loading = true;
    this.error = null;
    try {
      this.currentFolderId = id;
      this.expandPathTo(id);

      this.childFolders = await this.api.getFoldersByParent(id);
      this.files = id === null ? [] : await this.api.getFiles(id);

      const pathNodes = id !== null ? this.getPathNodes(this.folderTree, id) : null;
      this.currentFolderPath = pathNodes
        ? pathNodes.map((n) => ({ id: n.id, name: n.name, parentId: null, createdAt: '', updatedAt: '' }))
        : [];
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async createFolder(): Promise<void> {
    const name = window.prompt('Имя новой папки:');
    if (!name) return;
    this.loading = true;
    this.error = null;
    try {
      await this.api.createFolder(name, this.currentFolderId);
      await this.loadTree();
      await this.selectFolder(this.currentFolderId);
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async renameFolder(folder: { id: string; name: string }): Promise<void> {
    const name = window.prompt('Новое имя папки:', folder.name);
    if (!name || name === folder.name) return;
    this.loading = true;
    this.error = null;
    try {
      await this.api.renameFolder(folder.id, name);
      await this.loadTree();
      await this.selectFolder(this.currentFolderId);
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async deleteFolder(folder: { id: string; name: string }): Promise<void> {
    if (!window.confirm(`Удалить папку "${folder.name}" и всё её содержимое?`)) return;
    this.loading = true;
    this.error = null;
    try {
      await this.api.deleteFolder(folder.id);
      await this.loadTree();
      await this.selectFolder(this.currentFolderId === folder.id ? null : this.currentFolderId);
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async onFilesSelected(e: Event): Promise<void> {
    if (this.currentFolderId === null) return;
    const input = e.target as HTMLInputElement;
    if (!input.files?.length) return;
    this.loading = true;
    this.error = null;
    try {
      for (const file of Array.from(input.files)) {
        await this.api.uploadFile(this.currentFolderId, file);
      }
      input.value = '';
      await this.loadTree();
      await this.selectFolder(this.currentFolderId);
    } catch (err) {
      this.error = err instanceof Error ? err.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async renameFile(file: FileItem): Promise<void> {
    const name = window.prompt('Новое имя файла:', file.name);
    if (!name || name === file.name) return;
    this.loading = true;
    this.error = null;
    try {
      await this.api.renameFile(file.id, name);
      await this.loadTree();
      await this.selectFolder(this.currentFolderId);
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async deleteFile(file: FileItem): Promise<void> {
    if (!window.confirm(`Удалить файл "${file.name}"?`)) return;
    this.loading = true;
    this.error = null;
    try {
      await this.api.deleteFile(file.id);
      await this.loadTree();
      await this.selectFolder(this.currentFolderId);
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async createRoadmap(): Promise<void> {
    if (this.currentFolderId === null) return;
    const name = window.prompt('Имя файла роадмапа:', 'Роадмап.roadmap')?.trim();
    if (!name) return;
    const finalName = name.endsWith('.roadmap') ? name : name + '.roadmap';
    const initial: RoadmapData = { title: 'Роадмап', nodes: [] };
    const blob = new Blob([JSON.stringify(initial, null, 2)], { type: 'application/json' });
    const file = new File([blob], finalName, { type: 'application/json' });
    this.loading = true;
    this.error = null;
    try {
      const created = await this.api.uploadFile(this.currentFolderId, file);
      await this.loadTree();
      await this.selectFolder(this.currentFolderId);
      this.editingRoadmapFile = created;
      this.roadmapData = initial;
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async openRoadmap(file: FileItem): Promise<void> {
    this.loading = true;
    this.error = null;
    try {
      const data = await this.api.getFileContent(file.id);
      this.editingRoadmapFile = file;
      this.roadmapData = data;
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  async saveRoadmap(data: RoadmapData): Promise<void> {
    if (!this.editingRoadmapFile) return;
    this.roadmapSaving = true;
    try {
      await this.api.putFileContent(this.editingRoadmapFile.id, data);
      await this.loadTree();
      this.closeRoadmapEditor();
    } finally {
      this.roadmapSaving = false;
    }
  }

  closeRoadmapEditor(): void {
    this.editingRoadmapFile = null;
    this.roadmapData = null;
  }

  onDragOver(e: DragEvent): void {
    e.preventDefault();
    e.stopPropagation();
    if (this.currentFolderId !== null && e.dataTransfer?.types.includes('Files'))
      this.dropZoneActive = true;
  }

  onDragLeave(e: DragEvent): void {
    e.preventDefault();
    e.stopPropagation();
    this.dropZoneActive = false;
  }

  async onDrop(e: DragEvent): Promise<void> {
    e.preventDefault();
    e.stopPropagation();
    this.dropZoneActive = false;
    if (this.currentFolderId === null) return;
    const files = e.dataTransfer?.files;
    if (!files?.length) return;
    this.loading = true;
    this.error = null;
    try {
      for (const file of Array.from(files)) {
        await this.api.uploadFile(this.currentFolderId, file);
      }
      await this.loadTree();
      await this.selectFolder(this.currentFolderId);
    } catch (err) {
      this.error = err instanceof Error ? err.message : 'Неизвестная ошибка';
    } finally {
      this.loading = false;
    }
  }

  getFileDownloadUrl(fileId: string): string {
    return this.api.getFileDownloadUrl(fileId);
  }

  formatSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' Б';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' КБ';
    return (bytes / (1024 * 1024)).toFixed(1) + ' МБ';
  }
}

<main class="app">
  <header class="app-header">
    <h1>Папки</h1>
    <div class="toolbar">
      <button (click)="createFolder()">Новая папка</button>
      <label class="upload-btn">
        Загрузить файлы
        <input type="file" multiple (change)="onFilesSelected($event)" />
      </label>
      @if (loading) {
        <span class="status">Загрузка...</span>
      }
      @if (error) {
        <span class="status error">{{ error }}</span>
      }
    </div>
  </header>

  <div class="app-body">
    <div class="panels">
      <aside class="tree-panel">
        <div class="tree-header">Папки</div>
        <div class="tree-scroll">
          @if (folderTree.length === 0 && !loading) {
            <p class="empty-hint">Нет папок</p>
          } @else {
            <app-folder-tree
              [tree]="folderTree"
              [filesByFolderId]="filesByFolderId"
              [selectedId]="currentFolderId"
              [expandedIds]="expandedIds"
              (selectFolder)="selectFolder($event)"
              (renameFolder)="renameFolder($event)"
              (deleteFolder)="deleteFolder($event)"
              (renameFile)="renameFile($event)"
              (deleteFile)="deleteFile($event)"
              (openRoadmap)="openRoadmap($event)"
              (expandToggle)="onExpandToggle($event)"
            />
          }
        </div>
      </aside>

      <section class="content-panel">
        <nav class="breadcrumbs">
          <button
            type="button"
            class="crumb"
            [class.current]="currentFolderId === null"
            (click)="selectFolder(null)"
          >
            Главная
          </button>
          @for (folder of currentFolderPath; track folder.id; let i = $index) {
            <span class="crumb-sep">/</span>
            <button
              type="button"
              class="crumb"
              [class.current]="i === currentFolderPath.length - 1"
              (click)="selectFolder(folder.id)"
            >
              {{ folder.name }}
            </button>
          }
        </nav>

        <div
          class="files-section"
          [class.drop-zone-active]="dropZoneActive"
          (dragover)="onDragOver($event)"
          (dragleave)="onDragLeave($event)"
          (drop)="onDrop($event)"
        >
          <div class="section-toolbar">
            <h2 class="section-title">Содержимое</h2>
            <div class="section-actions">
              <button type="button" (click)="createFolder()">Новая папка</button>
              @if (currentFolderId !== null) {
                <button type="button" (click)="createRoadmap()">Новый роадмап</button>
                <label class="upload-btn">
                  Загрузить файлы
                  <input type="file" multiple (change)="onFilesSelected($event)" />
                </label>
              } @else {
                <span class="upload-hint">Выберите папку для загрузки файлов</span>
              }
            </div>
          </div>
          @if (dropZoneActive) {
            <div class="drop-overlay">Отпустите файлы для загрузки в эту папку</div>
          }
          @if (childFolders.length === 0 && files.length === 0 && !dropZoneActive) {
            <p class="empty">
              @if (currentFolderId === null) {
                Нет папок. Создайте папку.
              } @else {
                В этой папке пусто. Создайте папку или перетащите сюда файлы.
              }
            </p>
          } @else if (!dropZoneActive) {
            <div class="items-list">
              @for (folder of childFolders; track folder.id) {
                <div class="item-row folder-row">
                  <span class="item-icon">📁</span>
                  <button type="button" class="item-name" (click)="selectFolder(folder.id)">
                    {{ folder.name }}
                  </button>
                  <div class="item-actions">
                    <button type="button" class="icon-btn" (click)="renameFolder(folder)" title="Переименовать">✎</button>
                    <button type="button" class="icon-btn" (click)="deleteFolder(folder)" title="Удалить">✕</button>
                  </div>
                </div>
              }
              @for (file of files; track file.id) {
                <div class="item-row file-row">
                  <span class="item-icon">{{ isRoadmapFile(file) ? '🗺' : '📄' }}</span>
                  @if (isRoadmapFile(file)) {
                    <button type="button" class="item-name item-link" (click)="openRoadmap(file)">
                      {{ file.name }}
                    </button>
                    <a [href]="getFileDownloadUrl(file.id)" target="_blank" rel="noreferrer" class="icon-btn" title="Скачать">📥</a>
                  } @else {
                    <a [href]="getFileDownloadUrl(file.id)" target="_blank" rel="noreferrer" class="item-name item-link">
                      {{ file.name }}
                    </a>
                  }
                  <span class="item-meta">{{ formatSize(file.size) }}</span>
                  <div class="item-actions">
                    <button type="button" class="icon-btn" (click)="renameFile(file)" title="Переименовать">✎</button>
                    <button type="button" class="icon-btn" (click)="deleteFile(file)" title="Удалить">✕</button>
                  </div>
                </div>
              }
            </div>
          }
        </div>
      </section>
    </div>

    @if (editingRoadmapFile && roadmapData) {
      <aside class="roadmap-panel">
        <app-roadmap-editor
          [file]="editingRoadmapFile"
          [data]="roadmapData"
          [saving]="roadmapSaving"
          (save)="saveRoadmap($event)"
          (close)="closeRoadmapEditor()"
        />
      </aside>
    }
  </div>
</main>

// frontend/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import type { Folder, FileItem } from './types'

  let loading = false
  let error: string | null = null

  let currentFolderId: string = 'root'
  let currentFolderPath: Folder[] = []
  let childFolders: Folder[] = []
  let files: FileItem[] = []

  onMount(async () => {
    await loadRoot()
  })

  async function loadRoot() {
    await selectFolder('root', true)
  }

  async function selectFolder(id: string, isRoot = false) {
    loading = true
    error = null
    try {
      currentFolderId = id

      const [foldersRes, filesRes] = await Promise.all([
        fetch(`/api/folders?parentId=${id === 'root' ? 'null' : id}`),
        fetch(`/api/files?folderId=${encodeURIComponent(id)}`),
      ])

      if (!foldersRes.ok || !filesRes.ok) {
        throw new Error('Ошибка загрузки данных')
      }

      childFolders = await foldersRes.json()
      files = await filesRes.json()

      await loadPath(id, isRoot)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Неизвестная ошибка'
    } finally {
      loading = false
    }
  }

  async function loadPath(id: string, isRoot: boolean) {
    if (isRoot || id === 'root') {
      currentFolderPath = [{ id: 'root', name: 'Root', parentId: null, createdAt: '', updatedAt: '' }]
      return
    }
    const res = await fetch('/api/folders?parentId=null')
    if (!res.ok) {
      currentFolderPath = []
      return
    }
    const rootFolders: Folder[] = await res.json()
    const root = rootFolders.find(f => f.id === 'root')
    if (!root) {
      currentFolderPath = []
      return
    }
    // Для простоты: показываем только текущую папку + Root,
    // без полного восстановления дерева по id родителя.
    const currentRes = await fetch(`/api/folders?parentId=${encodeURIComponent(root.id)}`)
    const children: Folder[] = currentRes.ok ? await currentRes.json() : []
    const current = children.find(f => f.id === id)
    currentFolderPath = current ? [root, current] : [root]
  }

  async function createFolder() {
    const name = window.prompt('Имя новой папки:')
    if (!name) return

    loading = true
    error = null
    try {
      const res = await fetch('/api/folders', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          parentId: currentFolderId === 'root' ? null : currentFolderId,
        }),
      })
      if (!res.ok) throw new Error('Не удалось создать папку')
      await selectFolder(currentFolderId)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Неизвестная ошибка'
    } finally {
      loading = false
    }
  }

  async function renameFolder(folder: Folder) {
    const name = window.prompt('Новое имя папки:', folder.name)
    if (!name || name === folder.name) return
    loading = true
    error = null
    try {
      const res = await fetch(`/api/folders/${folder.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name }),
      })
      if (!res.ok) throw new Error('Не удалось переименовать папку')
      await selectFolder(currentFolderId)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Неизвестная ошибка'
    } finally {
      loading = false
    }
  }

  async function deleteFolder(folder: Folder) {
    if (!window.confirm(`Удалить папку "${folder.name}" и всё её содержимое?`)) return
    loading = true
    error = null
    try {
      const res = await fetch(`/api/folders/${folder.id}`, {
        method: 'DELETE',
      })
      if (!res.ok) throw new Error('Не удалось удалить папку')
      await selectFolder(currentFolderId)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Неизвестная ошибка'
    } finally {
      loading = false
    }
  }

  async function onFilesSelected(event: Event) {
    const input = event.target as HTMLInputElement
    if (!input.files?.length) return

    loading = true
    error = null
    try {
      for (const file of Array.from(input.files)) {
        const formData = new FormData()
        formData.append('folderId', currentFolderId)
        formData.append('file', file)
        const res = await fetch('/api/files', {
          method: 'POST',
          body: formData,
        })
        if (!res.ok) {
          throw new Error(`Не удалось загрузить файл ${file.name}`)
        }
      }
      input.value = ''
      await selectFolder(currentFolderId)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Неизвестная ошибка'
    } finally {
      loading = false
    }
  }

  async function renameFile(file: FileItem) {
    const name = window.prompt('Новое имя файла:', file.name)
    if (!name || name === file.name) return
    loading = true
    error = null
    try {
      const res = await fetch(`/api/files/${file.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name }),
      })
      if (!res.ok) throw new Error('Не удалось переименовать файл')
      await selectFolder(currentFolderId)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Неизвестная ошибка'
    } finally {
      loading = false
    }
  }

  async function deleteFile(file: FileItem) {
    if (!window.confirm(`Удалить файл "${file.name}"?`)) return
    loading = true
    error = null
    try {
      const res = await fetch(`/api/files/${file.id}`, {
        method: 'DELETE',
      })
      if (!res.ok) throw new Error('Не удалось удалить файл')
      await selectFolder(currentFolderId)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Неизвестная ошибка'
    } finally {
      loading = false
    }
  }
</script>

<main class="app">
  <header class="app-header">
    <h1>Личная база знаний</h1>
  </header>

  <section class="toolbar">
    <button on:click={createFolder}>Новая папка</button>
    <label class="upload-btn">
      Загрузить файлы
      <input type="file" multiple on:change={onFilesSelected} />
    </label>
    {#if loading}
      <span class="status">Загрузка...</span>
    {/if}
    {#if error}
      <span class="status error">{error}</span>
    {/if}
  </section>

  <section class="breadcrumbs">
    {#each currentFolderPath as folder, index}
      <span
        class="crumb"
        on:click={() => selectFolder(folder.id, folder.id === 'root')}
      >
        {folder.name}
      </span>
      {#if index < currentFolderPath.length - 1}
        <span class="crumb-separator">/</span>
      {/if}
    {/each}
  </section>

  <section class="content">
    <aside class="sidebar">
      <h2>Папки</h2>
      {#if childFolders.length === 0}
        <p class="empty">Нет подпапок</p>
      {:else}
        <ul class="folder-list">
          {#each childFolders as folder}
            <li class="folder-item">
              <button
                class:active={folder.id === currentFolderId}
                on:click={() => selectFolder(folder.id)}
              >
                {folder.name}
              </button>
              <div class="folder-actions">
                <button on:click={() => renameFolder(folder)}>✎</button>
                <button on:click={() => deleteFolder(folder)}>✕</button>
              </div>
            </li>
          {/each}
        </ul>
      {/if}
    </aside>

    <section class="files">
      <h2>Файлы</h2>
      {#if files.length === 0}
        <p class="empty">Файлов нет</p>
      {:else}
        <table>
          <thead>
            <tr>
              <th>Имя</th>
              <th>Тип</th>
              <th>Размер</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {#each files as file}
              <tr>
                <td>
                  <a href={`/api/files/${file.id}/download`} target="_blank" rel="noreferrer">
                    {file.name}
                  </a>
                </td>
                <td>{file.mimeType}</td>
                <td>{Math.round(file.size / 1024)} КБ</td>
                <td class="file-actions">
                  <button on:click={() => renameFile(file)}>✎</button>
                  <button on:click={() => deleteFile(file)}>✕</button>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      {/if}
    </section>
  </section>
</main>

<style>
  :global(body) {
    margin: 0;
    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background-color: #0f172a;
    color: #e5e7eb;
  }

  .app {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
  }

  .app-header {
    padding: 1rem 1.5rem;
    border-bottom: 1px solid #1f2937;
    background: linear-gradient(to right, #020617, #111827);
  }

  .app-header h1 {
    margin: 0;
    font-size: 1.25rem;
  }

  .toolbar {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.75rem 1.5rem;
    border-bottom: 1px solid #1f2937;
    background-color: #020617;
  }

  button {
    background-color: #2563eb;
    color: #e5e7eb;
    border: none;
    border-radius: 0.375rem;
    padding: 0.4rem 0.75rem;
    cursor: pointer;
    font-size: 0.875rem;
  }

  button:hover {
    background-color: #1d4ed8;
  }

  .upload-btn {
    position: relative;
    overflow: hidden;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.4rem 0.75rem;
    border-radius: 0.375rem;
    background-color: #374151;
    cursor: pointer;
    font-size: 0.875rem;
  }

  .upload-btn input[type='file'] {
    position: absolute;
    inset: 0;
    opacity: 0;
    cursor: pointer;
  }

  .status {
    font-size: 0.875rem;
    color: #9ca3af;
  }

  .status.error {
    color: #fca5a5;
  }

  .breadcrumbs {
    padding: 0.5rem 1.5rem;
    border-bottom: 1px solid #1f2937;
    background-color: #020617;
    font-size: 0.875rem;
  }

  .crumb {
    cursor: pointer;
    color: #60a5fa;
  }

  .crumb:hover {
    text-decoration: underline;
  }

  .crumb-separator {
    margin: 0 0.25rem;
    color: #6b7280;
  }

  .content {
    flex: 1;
    display: grid;
    grid-template-columns: 260px 1fr;
    min-height: 0;
  }

  .sidebar {
    border-right: 1px solid #1f2937;
    padding: 0.75rem 1rem;
    background-color: #020617;
  }

  .sidebar h2,
  .files h2 {
    margin: 0 0 0.75rem;
    font-size: 0.95rem;
    color: #9ca3af;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .folder-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .folder-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.25rem;
  }

  .folder-item > button {
    flex: 1;
    text-align: left;
    background-color: transparent;
    padding: 0.25rem 0.5rem;
    border-radius: 0.375rem;
  }

  .folder-item > button:hover {
    background-color: #111827;
  }

  .folder-item > button.active {
    background-color: #1d4ed8;
  }

  .folder-actions button {
    background: transparent;
    color: #9ca3af;
    padding: 0.2rem;
  }

  .folder-actions button:hover {
    color: #e5e7eb;
    background: transparent;
  }

  .files {
    padding: 0.75rem 1rem;
    overflow: auto;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
  }

  th,
  td {
    padding: 0.4rem 0.5rem;
    border-bottom: 1px solid #1f2937;
  }

  th {
    text-align: left;
    color: #9ca3af;
    font-weight: 500;
  }

  a {
    color: #e5e7eb;
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }

  .file-actions button {
    background: transparent;
    color: #9ca3af;
    padding: 0.2rem;
  }

  .file-actions button:hover {
    color: #e5e7eb;
  }

  .empty {
    font-size: 0.875rem;
    color: #6b7280;
  }

  @media (max-width: 768px) {
    .content {
      grid-template-columns: 1fr;
    }

    .sidebar {
      border-right: none;
      border-bottom: 1px solid #1f2937;
    }
  }
</style>
